In [1]:
import pandas as pd
import numpy as np
import seaborn as sns 

In [3]:
from sklearn.datasets import make_classification

In [4]:
X,y = make_classification(n_samples=1000, n_features=10, n_classes=3, n_informative=5, n_redundant=5, random_state=42)

In [5]:
X

array([[ 2.59014356, -3.42407256,  0.26830895, ..., -0.4075564 ,
         2.00889958,  0.91176128],
       [-0.18964388,  1.18915349,  1.33715288, ...,  0.75174259,
        -0.93616979, -0.0406729 ],
       [ 2.33823479,  1.73171672, -2.9554549 , ..., -6.11310542,
         2.56981847,  0.49067355],
       ...,
       [-5.0147105 ,  2.6321196 , -1.85549514, ...,  0.2517947 ,
        -1.09326259, -2.72779634],
       [-1.59943891,  1.68834032,  1.06411267, ...,  0.93209456,
        -1.11081933, -1.08072112],
       [ 2.89511603, -4.213598  ,  1.43221441, ...,  2.97446066,
        -0.86821862,  0.73856138]])

In [6]:
y

array([0, 0, 1, 0, 0, 1, 2, 2, 0, 2, 1, 2, 1, 2, 1, 1, 0, 2, 2, 2, 1, 0,
       0, 0, 2, 2, 1, 1, 2, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 1, 1, 1, 2,
       2, 2, 1, 2, 0, 2, 0, 0, 0, 0, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 1, 1,
       2, 1, 1, 0, 1, 1, 1, 1, 1, 2, 0, 0, 0, 2, 2, 2, 2, 0, 2, 0, 1, 1,
       2, 0, 0, 1, 0, 0, 1, 2, 1, 2, 1, 0, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 2, 0, 1, 0, 1, 1, 0, 2, 0, 1, 0, 2, 0,
       2, 0, 1, 2, 2, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1,
       0, 1, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 2,
       0, 0, 0, 1, 1, 2, 0, 1, 0, 1, 1, 1, 2, 0, 2, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1, 2, 0, 2, 2, 1, 1, 2, 2, 0, 1, 1,
       0, 0, 2, 1, 0, 0, 1, 0, 0, 2, 2, 1, 2, 2, 0, 0, 1, 1, 0, 2, 0, 0,
       0, 2, 2, 2, 0, 2, 1, 1, 0, 2, 2, 1, 1, 2, 2, 0, 2, 1, 0, 2, 1, 2,
       1, 2, 0, 2, 0, 0, 0, 2, 0, 1, 1, 2, 1, 0, 1, 0, 2, 1, 0, 2, 0, 2,
       0, 2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 2, 0, 0, 1,

In [7]:
from sklearn.linear_model import LogisticRegression

In [13]:
model = LogisticRegression(multi_class="multinomial",solver="lbfgs")

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=42)

In [11]:
X_test.shape, X_train.shape ,y_train.shape, y_test.shape

((300, 10), (700, 10), (700,), (300,))

In [14]:
model.fit(X_train,y_train)

LogisticRegression(multi_class='multinomial')

In [15]:
y_pre = model.predict(X_test)

In [16]:
y_pre

array([1, 0, 2, 1, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2, 1, 2, 2,
       0, 0, 0, 0, 1, 2, 2, 0, 1, 0, 2, 2, 1, 1, 0, 1, 1, 0, 0, 2, 2, 2,
       2, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 2, 1, 0, 1, 1, 0, 0, 2, 1, 2,
       0, 0, 1, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 2, 2, 1, 2, 2, 2, 2,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 2, 2, 2, 1, 0, 1, 1, 2, 1, 1, 1, 0, 1,
       2, 0, 0, 1, 1, 2, 0, 1, 2, 1, 2, 0, 1, 0, 0, 0, 1, 2, 0, 2, 0, 0,
       2, 1, 0, 1, 0, 1, 2, 1, 2, 2, 1, 0, 2, 0, 2, 2, 1, 1, 0, 0, 0, 2,
       1, 0, 1, 0, 2, 1, 1, 2, 1, 0, 0, 1, 0, 0, 1, 2, 2, 0, 2, 1, 1, 2,
       1, 1, 2, 0, 1, 1, 0, 0, 2, 2, 1, 2, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 2, 0, 2, 0, 0, 2, 0, 1, 1, 1, 0, 2, 0, 1, 0, 2, 1,
       0, 0, 2, 2, 2, 1, 0, 1, 2, 1, 2, 1, 2, 0, 2, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 2, 0, 2, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 0, 2, 0,
       0, 0, 2, 1, 2, 0, 1, 1, 2, 0, 0, 2, 0, 2, 1, 1, 0, 0, 1, 2, 1, 0,
       0, 0, 0, 2, 1, 0, 0, 2, 1, 0, 0, 0, 0, 1])

In [19]:
from sklearn.metrics import classification_report, accuracy_score ,confusion_matrix

In [21]:
print(classification_report(y_test,y_pre))

              precision    recall  f1-score   support

           0       0.77      0.82      0.79       106
           1       0.67      0.74      0.71        94
           2       0.72      0.60      0.66       100

    accuracy                           0.72       300
   macro avg       0.72      0.72      0.72       300
weighted avg       0.72      0.72      0.72       300



In [22]:
accuracy_score(y_test,y_pre)

0.7233333333333334

In [23]:
confusion_matrix(y_test,y_pre)

array([[87,  7, 12],
       [13, 70, 11],
       [13, 27, 60]], dtype=int64)

In [24]:
## number of category is = 3 than confusion matrix size will be 3X3
## number of category is = 4 than confusion matrix size will be 4X4
## diagonal points are accurate 

In [25]:
model_2 = LogisticRegression(multi_class="ovr",solver="lbfgs")

In [26]:
model_2.fit(X_train,y_train)

LogisticRegression(multi_class='ovr')

In [29]:
y_predict = model_2.predict(X_test)

In [28]:
model_2.predict_proba(X_test)

array([[1.31342385e-01, 6.47100314e-01, 2.21557301e-01],
       [4.20183189e-01, 4.14055063e-01, 1.65761748e-01],
       [3.01131456e-01, 3.74902172e-01, 3.23966372e-01],
       [6.18193380e-03, 6.87125272e-01, 3.06692794e-01],
       [5.98065345e-01, 4.86999850e-02, 3.53234670e-01],
       [6.99733963e-01, 2.49796752e-04, 3.00016240e-01],
       [6.31294506e-02, 5.73495812e-01, 3.63374737e-01],
       [4.00749543e-01, 1.21796534e-01, 4.77453923e-01],
       [1.80416651e-01, 3.76982731e-01, 4.42600617e-01],
       [3.58989422e-01, 1.82349711e-01, 4.58660867e-01],
       [4.79473662e-01, 1.45720913e-01, 3.74805425e-01],
       [8.03881803e-01, 9.12603217e-03, 1.86992164e-01],
       [5.73118298e-01, 9.10344116e-03, 4.17778261e-01],
       [7.81846992e-01, 1.11161186e-02, 2.07036890e-01],
       [6.78156631e-01, 5.54720179e-02, 2.66371351e-01],
       [6.83374637e-01, 1.31879402e-02, 3.03437423e-01],
       [3.90854341e-01, 1.10623626e-01, 4.98522033e-01],
       [6.72866513e-02, 5.16916

In [30]:
y_predict

array([1, 0, 1, 1, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 1, 2, 1, 2, 2,
       0, 0, 0, 0, 1, 2, 0, 0, 1, 0, 2, 2, 1, 1, 0, 1, 1, 0, 0, 2, 2, 2,
       2, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 2, 1, 0, 1, 1, 0, 0, 2, 1, 0,
       0, 0, 1, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 2, 2, 1, 2, 2, 0, 2,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 2, 2, 2, 1, 0, 1, 1, 2, 1, 1, 2, 0, 1,
       2, 0, 0, 1, 1, 2, 0, 1, 2, 1, 2, 0, 1, 0, 0, 0, 1, 2, 2, 2, 0, 0,
       2, 1, 0, 1, 0, 1, 2, 1, 0, 2, 1, 0, 2, 0, 2, 2, 1, 1, 0, 0, 0, 2,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 1, 1, 2,
       1, 1, 2, 0, 1, 1, 0, 0, 2, 2, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 2, 0, 0, 2, 0, 1, 1, 1, 0, 0, 0, 1, 0, 2, 1,
       0, 0, 2, 2, 2, 1, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 2, 0, 2, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 0, 2, 0,
       0, 0, 2, 1, 2, 0, 1, 1, 2, 0, 0, 2, 0, 2, 1, 1, 0, 0, 1, 2, 1, 0,
       0, 0, 0, 2, 1, 0, 0, 2, 2, 0, 0, 0, 0, 1])

In [32]:
confusion_matrix(y_test,y_predict)

array([[88,  7, 11],
       [13, 70, 11],
       [19, 29, 52]], dtype=int64)

In [33]:
accuracy_score(y_test,y_predict)

0.7

In [35]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.73      0.83      0.78       106
           1       0.66      0.74      0.70        94
           2       0.70      0.52      0.60       100

    accuracy                           0.70       300
   macro avg       0.70      0.70      0.69       300
weighted avg       0.70      0.70      0.69       300

