In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, recall_score, f1_score

In [2]:
from sklearn.datasets import load_iris

In [3]:
dataset = load_iris()

In [4]:
dataset.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

In [7]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [8]:
df = pd.DataFrame(dataset["data"],columns=dataset.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [15]:
df["y"] = dataset["target"]
df.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  y
0                5.1               3.5                1.4               0.2  0
1                4.9               3.0                1.4               0.2  0
2                4.7               3.2                1.3               0.2  0
3                4.6               3.1                1.5               0.2  0
4                5.0               3.6                1.4               0.2  0

In [11]:
dataset.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [12]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [16]:
df.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  y
0                5.1               3.5                1.4               0.2  0
1                4.9               3.0                1.4               0.2  0
2                4.7               3.2                1.3               0.2  0
3                4.6               3.1                1.5               0.2  0
4                5.0               3.6                1.4               0.2  0

In [17]:
df["y"].unique()

array([0, 1, 2])

In [18]:
df["y"].nunique()

3

In [19]:
df.tail(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     y  
145  2  
146  2  
147  2  
148  2  
149  2

In [20]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)           y  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [22]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
y                    0
dtype: int64

In [24]:
df.size

750

In [25]:
df.shape

(150, 5)

In [26]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'y'],
      dtype='object')

In [27]:
X = df.drop(["y"],axis=1)
y = df["y"]
X.shape,y.shape

((150, 4), (150,))

In [28]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [29]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: y, Length: 150, dtype: int32

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=42)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((105, 4), (45, 4), (105,), (45,))

In [32]:
X_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
81                 5.5               2.4                3.7               1.0
133                6.3               2.8                5.1               1.5
137                6.4               3.1                5.5               1.8
75                 6.6               3.0                4.4               1.4
109                7.2               3.6                6.1               2.5
..                 ...               ...                ...               ...
71                 6.1               2.8                4.0               1.3
106                4.9               2.5                4.5               1.7
14                 5.8               4.0                1.2               0.2
92                 5.8               2.6                4.0               1.2
102                7.1               3.0                5.9               2.1

[105 rows x 4 columns]

In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
logistic = LogisticRegression()

In [35]:
logistic.fit(X_train,y_train)

LogisticRegression()

In [36]:
y_hat = logistic.predict(X_test)

In [37]:
logistic.coef_

array([[-0.40451038,  0.86880598, -2.27810348, -0.95717997],
       [ 0.46657894, -0.37531029, -0.18748075, -0.72091703],
       [-0.06206856, -0.49349569,  2.46558423,  1.678097  ]])

In [38]:
logistic.fit_intercept

True

In [39]:
logistic.intercept_

array([  8.86043362,   2.2097759 , -11.07020952])

In [42]:
logistic.max_iter

100

In [43]:
logistic.penalty

'l2'

In [44]:
logistic.solver

'lbfgs'

In [46]:
y_hat

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [47]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [48]:
confusion_matrix(y_test,y_hat)

array([[19,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]], dtype=int64)

In [50]:
print(classification_report(y_test,y_hat))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [53]:
accuracy_score(y_test,y_hat)

1.0

In [54]:
# precision_score, recall_score, f1_score --> this is only used for binary class classification

In [55]:
## cross valdation

In [57]:
from sklearn.model_selection import KFold

In [58]:
k_flod = KFold(n_splits=3)

In [59]:
k_flod

KFold(n_splits=3, random_state=None, shuffle=False)

In [63]:
X_train.shape,y_train.shape

((105, 4), (105,))

In [62]:
from sklearn.model_selection import cross_val_score

In [64]:
logistic

LogisticRegression()

In [66]:
score  = cross_val_score(logistic,X_train,y_train,scoring="accuracy",cv=k_flod)
score

array([1.        , 0.91428571, 0.97142857])

In [67]:
np.mean(score)

0.9619047619047619

In [68]:
###

In [69]:
from sklearn.datasets import make_classification


In [71]:
X,y = make_classification(n_samples=1000,n_features=10,n_classes=2,n_clusters_per_class=1,random_state=20,n_redundant=5)

In [72]:
X,y

(array([[ 0.66939602,  0.24132021, -0.40428949, ..., -1.31902494,
          1.14064321,  0.4104589 ],
        [-0.43372546, -0.40890741, -0.21431182, ...,  0.68894324,
          0.71961639,  0.19900535],
        [ 0.13790084,  0.83806914,  0.02011735, ..., -0.46544057,
          1.94024766,  0.62811382],
        ...,
        [-1.82772844,  0.1279377 ,  1.99541839, ...,  3.26330041,
         -0.13734582, -0.17177342],
        [-1.37795098, -1.50707002, -1.66497175, ...,  2.44742217,
          0.00937396, -0.09350875],
        [ 0.7307074 , -0.43635652, -0.3007165 , ..., -1.48136989,
          1.61073531,  0.56459501]]),
 array([0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
        1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
        1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
        0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
        1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
   

In [73]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=20,random_state=42)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((980, 10), (20, 10), (980,), (20,))

In [74]:
logi = LogisticRegression()

In [75]:
logi.fit(X_train,y_train)


LogisticRegression()

In [76]:
y_pre = logi.predict(X_test)

In [78]:
print(classification_report(y_test,y_pre))

              precision    recall  f1-score   support

           0       0.90      0.75      0.82        12
           1       0.70      0.88      0.78         8

    accuracy                           0.80        20
   macro avg       0.80      0.81      0.80        20
weighted avg       0.82      0.80      0.80        20



In [79]:
accuracy_score(y_test,y_pre)

0.8

In [80]:
confusion_matrix(y_test,y_pre)

array([[9, 3],
       [1, 7]], dtype=int64)

In [81]:
## now improve 

In [82]:
k_flod_ = KFold(n_splits= 8)

In [83]:
score = cross_val_score(logi,X_train,y_train,scoring="accuracy",cv=k_flod_)
score

array([0.88617886, 0.77235772, 0.80487805, 0.8699187 , 0.79508197,
       0.81967213, 0.81967213, 0.86065574])

In [84]:
np.mean(score)

0.8285519125683061

In [ ]:
## hyperparameters tunning 

In [85]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [86]:
X_train

array([[ 0.62240714,  0.11131305,  2.21608446, ..., -1.21888788,
         0.99413855,  0.36046973],
       [ 0.02901193, -0.00638806, -0.02493459, ..., -0.22148587,
         1.49595705,  0.47887015],
       [-0.68114315,  0.69250827, -1.08690968, ...,  1.14978269,
         0.53297301,  0.12218605],
       ...,
       [-0.75053706, -0.02182   ,  1.75868157, ...,  1.34223765,
        -0.07575215, -0.07670557],
       [-0.42035628, -0.68518516, -0.72098273, ...,  0.68225202,
         0.56939475,  0.15205821],
       [-0.75380934,  0.42527406, -1.53637685, ...,  1.29596682,
         0.38276264,  0.06921753]])

In [87]:
y_train

array([1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,

In [88]:
import warnings
warnings.filterwarnings("ignore")

In [89]:
params = {
    "penalty" : ["l1","l2", "elasticnet"],
    "C" : [1,5,8,10]
}

In [90]:
params

{'penalty': ['l1', 'l2', 'elasticnet'], 'C': [1, 5, 8, 10]}

In [91]:
logistic = LogisticRegression()

In [92]:
logistic

LogisticRegression()

In [94]:
grid_search = GridSearchCV(logistic,scoring="accuracy",param_grid=params,cv=5)

In [95]:
grid_search.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 5, 8, 10],
                         'penalty': ['l1', 'l2', 'elasticnet']},
             scoring='accuracy')

In [96]:
y_predict  = grid_search.predict(X_test)

In [97]:
grid_search.best_estimator_

LogisticRegression(C=1)

In [98]:
grid_search.best_params_

{'C': 1, 'penalty': 'l2'}

In [99]:
grid_search.best_score_

0.8326530612244897

In [101]:
logistic_new = LogisticRegression(C= 1, penalty= 'l2')

In [102]:
logistic_new.fit(X_train,y_train)

LogisticRegression(C=1)

In [103]:
y_predict = logistic_new.predict(X_test)

In [104]:
accuracy_score(y_test,y_predict)

0.8

In [106]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.90      0.75      0.82        12
           1       0.70      0.88      0.78         8

    accuracy                           0.80        20
   macro avg       0.80      0.81      0.80        20
weighted avg       0.82      0.80      0.80        20



In [107]:
confusion_matrix(y_test,y_predict)

array([[9, 3],
       [1, 7]], dtype=int64)

In [108]:
logistic_new.predict(X_test)

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1])

In [109]:
logistic_new.predict_proba(X_test)

array([[0.25985245, 0.74014755],
       [0.96411396, 0.03588604],
       [0.97194237, 0.02805763],
       [0.85681668, 0.14318332],
       [0.81004934, 0.18995066],
       [0.48475382, 0.51524618],
       [0.97614305, 0.02385695],
       [0.61508757, 0.38491243],
       [0.90921433, 0.09078567],
       [0.26944072, 0.73055928],
       [0.98349135, 0.01650865],
       [0.95322581, 0.04677419],
       [0.08877786, 0.91122214],
       [0.03787597, 0.96212403],
       [0.21075082, 0.78924918],
       [0.35511   , 0.64489   ],
       [0.51437574, 0.48562426],
       [0.17218262, 0.82781738],
       [0.33417186, 0.66582814],
       [0.01591151, 0.98408849]])

In [111]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.linear_model import LogisticRegression

logi = LogisticRegression()

In [112]:
random = RandomizedSearchCV(logi,param_distributions=params,cv=5,n_iter=12,scoring="accuracy")

In [113]:
random

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=12,
                   param_distributions={'C': [1, 5, 8, 10],
                                        'penalty': ['l1', 'l2', 'elasticnet']},
                   scoring='accuracy')

In [114]:
random.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=12,
                   param_distributions={'C': [1, 5, 8, 10],
                                        'penalty': ['l1', 'l2', 'elasticnet']},
                   scoring='accuracy')

In [115]:
y_predict = random.predict(X_test)

In [116]:
accuracy_score(y_test,y_predict)

0.8

In [117]:
random.best_estimator_

LogisticRegression(C=1)

In [118]:
random.best_params_

{'penalty': 'l2', 'C': 1}

In [119]:
random.best_score_

0.8326530612244897

In [120]:
random.best_index_

1

In [122]:
ll = LogisticRegression(penalty= 'l2', C= 1)
ll

LogisticRegression(C=1)

In [123]:
ll.fit(X_train,y_train)

LogisticRegression(C=1)

In [124]:
y_hat = ll.predict(X_test)

In [125]:
accuracy_score(y_test,y_hat)

0.8

In [126]:
print(classification_report(y_test,y_hat))

              precision    recall  f1-score   support

           0       0.90      0.75      0.82        12
           1       0.70      0.88      0.78         8

    accuracy                           0.80        20
   macro avg       0.80      0.81      0.80        20
weighted avg       0.82      0.80      0.80        20



In [127]:
confusion_matrix(y_test,y_hat)

array([[9, 3],
       [1, 7]], dtype=int64)

In [128]:
X,y = make_classification(n_samples=1000,n_features=7,n_classes=3,n_informative=5,random_state=1,n_clusters_per_class=1)
X,y

(array([[ 0.82990309,  1.86781577,  0.93547484, ..., -1.84496879,
          0.66740016, -2.03205898],
        [ 1.29042195,  2.34513454, -1.54590454, ..., -2.56269884,
         -0.76439758, -0.0520262 ],
        [ 2.96500558, -1.09414913, -0.90399383, ..., -1.28601402,
          2.64365689,  0.61110232],
        ...,
        [ 2.23975692, -1.44517368, -3.79672191, ...,  0.50009679,
          2.72016649,  3.22302473],
        [-0.78457043,  1.40174485,  0.11204557, ..., -1.604444  ,
          1.9327265 ,  2.07897303],
        [ 0.54129938,  0.71863078, -0.25856498, ..., -2.05806478,
          2.40734928,  2.13439593]]),
 array([0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 1, 1, 1, 0, 0, 0, 2, 1, 1, 1, 2, 2,
        0, 0, 2, 1, 2, 2, 2, 0, 1, 2, 1, 0, 2, 1, 2, 0, 2, 2, 0, 0, 1, 0,
        0, 0, 1, 1, 1, 0, 0, 2, 0, 2, 1, 0, 2, 2, 1, 2, 1, 2, 0, 2, 0, 0,
        1, 1, 1, 0, 0, 2, 1, 0, 2, 2, 0, 1, 1, 2, 2, 1, 2, 2, 0, 0, 2, 0,
        1, 2, 2, 1, 1, 2, 0, 0, 0, 2, 0, 1, 2, 0, 1, 0, 1, 0, 0, 2, 1, 1,
   

In [130]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=42)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((700, 7), (300, 7), (700,), (300,))

In [131]:
from sklearn.linear_model import LogisticRegression

In [132]:
multi = LogisticRegression(multi_class = "ovr",solver="lbfgs")

In [133]:
multi.fit(X_train,y_train)

LogisticRegression(multi_class='ovr')

In [135]:
y_pred = multi.predict(X_test)

In [136]:
accuracy_score(y_test,y_pred)

0.9466666666666667

In [138]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.97      0.95      0.96       107
           1       0.93      0.91      0.92        94
           2       0.93      0.97      0.95        99

    accuracy                           0.95       300
   macro avg       0.95      0.95      0.95       300
weighted avg       0.95      0.95      0.95       300



In [139]:
confusion_matrix(y_test,y_pred)

array([[102,   4,   1],
       [  2,  86,   6],
       [  1,   2,  96]], dtype=int64)

In [141]:
multi.predict_proba(X_test)

array([[2.55462682e-06, 1.17980848e-01, 8.82016597e-01],
       [9.55638608e-01, 6.65677578e-03, 3.77046167e-02],
       [2.44182777e-02, 4.07582581e-04, 9.75174140e-01],
       [9.11473952e-01, 8.84282748e-02, 9.77730170e-05],
       [8.34724951e-01, 1.63551368e-01, 1.72368112e-03],
       [3.77584961e-05, 6.41919544e-01, 3.58042697e-01],
       [6.69960880e-01, 9.00033197e-04, 3.29139087e-01],
       [1.93059494e-03, 6.62077960e-02, 9.31861609e-01],
       [9.81474253e-01, 1.13269914e-02, 7.19875585e-03],
       [8.81380221e-01, 6.22300624e-04, 1.17997478e-01],
       [2.54873059e-03, 9.96175604e-01, 1.27566517e-03],
       [9.45562762e-01, 4.70343935e-02, 7.40284486e-03],
       [2.26679398e-06, 9.99644490e-01, 3.53243583e-04],
       [3.16469020e-02, 9.66799015e-01, 1.55408294e-03],
       [7.25011073e-05, 9.99151621e-01, 7.75877756e-04],
       [9.93221641e-01, 4.17373854e-03, 2.60462080e-03],
       [9.84798291e-01, 1.24709869e-02, 2.73072227e-03],
       [4.44014106e-05, 9.60338